---
- hosts: load_balancer
  become: yes
  vars:
    app_ips:
     - 172.31.11.38:8080

  tasks:
    - name: install epel
      yum:
        name: 
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: latest
       
    - name: install nginx
      yum:
        name:
        - nginx
        state: latest

    - name: put nginx conf
      template:
        src: files/lb.conf
        dest: /etc/nginx/conf.d/blog.conf

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

  
- hosts: flask_app
  become: yes
  vars:
   APP_NAME: flaskapp
   REPO: https://github.com/kudseb/flaskprototype
  tasks:
   - name: install python
     yum:
      name:
      - python3
      - python3-pip
      - git
      state: latest



   - name: sync repo
     git:
      repo: "{{REPO}}"
      dest: /opt/{{APP_NAME}}

   - name: create user
     user:
      name: "{{APP_NAME}}"

   - name: Install virtualenv via pip
     pip:
      name: virtualenv
      executable: pip3
      
   - name: create venv and install packages
     pip:
      requirements: /opt/{{APP_NAME}}/requirements.txt
      virtualenv: /opt/{{APP_NAME}}/.venv
      virtualenv_command: 'python3 -m venv'
      
   - name: put systemd cfg
     template:
      src: files/flaskapp.service
      dest: /etc/systemd/system/{{APP_NAME}}.service

   - name: start service
     systemd:
      state: restarted
      daemon_reload: yes
      name: "{{APP_NAME}}"

  
